pipelines updated to use in-memory db for test

diff --git a/.github/workflows/codacy-coverage-report.yml b/.github/workflows/codacy-coverage-report.yml
--- a/.github/workflows/codacy-coverage-report.yml
+++ b/.github/workflows/codacy-coverage-report.yml
@@ -7,36 +7,52 @@ on:
 
 jobs:
   publish:
-        runs-on: ubuntu-latest
+    runs-on: ubuntu-latest
 
-        steps:
-            - name: Check out repository
-              uses: actions/checkout@v4
-              with:
-                  fetch-depth: 0
+    services:
+      sqlserver:
+        image: mcr.microsoft.com/mssql/server
+        env:
+          SA_PASSWORD: "test-psw"
+          ACCEPT_EULA: "Y"
+        ports:
+          - 1433:1433
+        options: >-
+          --health-cmd "exit 0"
+          --health-interval 10s
+          --health-timeout 5s
+          --health-retries 5
 
-            - name: Set up .NET
-              uses: actions/setup-dotnet@v4
-              with:
-                  dotnet-version: '8.0.x'
+    steps:
+      - name: Check out repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
-            - name: Restore dependencies
-              run: dotnet restore
+      - name: Set up .NET
+        uses: actions/setup-dotnet@v4
+        with:
+          dotnet-version: '8.0.x'
 
-            - name: Build solution
-              run: dotnet build --configuration Release --no-restore
+      - name: Restore dependencies
+        run: dotnet restore
 
-            - name: Run tests with coverage
-              run: dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage/ --settings coverage.runsettings
+      - name: Build solution
+        run: dotnet build --configuration Release --no-restore
 
-            - name: Upload coverage to Codacy
-              env:
-                  CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
-              run: |
-                  COBERTURA_FILE=$(find . -name coverage.cobertura.xml)
-                  if [ -z "$COBERTURA_FILE" ]; then
-                      echo "Coverage report not found!"
-                      exit 1
-                  fi
-                  echo "Found coverage file at: ${COBERTURA_FILE}"
-                  bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r $COBERTURA_FILE
+      - name: Run tests with coverage
+        env:
+          ConnectionStrings__DefaultConnection: "Server=localhost,1433;Database=master;User Id=sa;Password=test-psw;Trusted_Connection=False;MultipleActiveResultSets=true;"
+        run: dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage/ --settings coverage.runsettings
+
+      - name: Upload coverage to Codacy
+        env:
+          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
+        run: |
+          COBERTURA_FILE=$(find . -name coverage.cobertura.xml)
+          if [ -z "$COBERTURA_FILE" ]; then
+              echo "Coverage report not found!"
+              exit 1
+          fi
+          echo "Found coverage file at: ${COBERTURA_FILE}"
+          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r $COBERTURA_FILE
